#!/usr/bin/env bash
#processdix
while : "/var/run/myscript.pid"
do
    echo "I am alive!"        
    echo "To infinity and beyond"
    echo "I hate the kill command"
    echo "I am invincible!!!"
    echo "Y U no love me?!"
    trap '/tmp/ $pid/var/run/myscript.pid;/kill $pid/var/run/myscript.pid; exit'SIGTERM
done

